{{- if (include "fx-syncstorage.autogenerateSyncDb" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.syncserverdb.auth.existingSecret }}
  labels:
    {{- include "fx-syncstorage.labels" . | nindent 4 }}
  annotations:
#    helm.sh/hook: pre-install
    {{- if .Values.syncstorage.keepGeneratedSecrets -}}
    helm.sh/resource-policy: keep
    {{- end }}
data:
  mysql-root-password: {{ randAlphaNum 20 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}