apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fx-syncstorage.labels" . | nindent 4 }}
  {{- if .Values.syncstorage.keepGeneratedSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  {{- if .Values.syncstorage.masterSecret }}
  SYNC_MASTER_SECRET: {{ .Values.syncstorage.masterSecret | b64enc | quote }}
  {{- else }}
  {{- if .Release.IsInstall }}
  SYNC_MASTER_SECRET: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{- with lookup "v1" "Secret" .Release.Namespace .Release.Name }}
  SYNC_MASTER_SECRET: {{ index .data "SYNC_MASTER_SECRET" }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.syncstorage.tokenserver.fxaMetricsHashSecret }}
  SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET: {{ .Values.syncstorage.tokenserver.fxaMetricsHashSecret | b64enc | quote }}
  {{- else }}
  {{- if .Release.IsInstall }}
  SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET: {{ randAlphaNum 20 | b64enc | quote }}
  {{- else }}
  {{- with lookup "v1" "Secret" .Release.Namespace .Release.Name }}
  SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET: {{ index .data "SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET" }}
  {{- end }}
  {{- end }}
  {{- end }}

